name: CI/CD Pipeline newera class24
on: 
  push:
    branches:
      - amadou

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: list files
        run: ls
      
      - name: ubuntu version
        run: lsb_release -a